title: Dale Dupree | Copier Warrior
description:
url: http://www.copierwarrior.com
markdown: kramdown
exclude:
- bower_components
- node_modules
- Gemfile*
- bower.json
- gulpfile.js
- package.json
defaults:
  - scope:
      path: ""
    values:
      layout: default
      fullname: Dale Dupree
      title: The Copier Warrior
      tagline: Man, Myth, Sales Guy.
      fact: I was born to serve
      bio: "I have been serving through this industry for over 10 years. My father before me is my mentor and the owner of the business where I sold my first copier, needless to say I have toner running through my blood. It is my goal to know and learn more about each individual business that I serve as I believe in a referral relationship and also knowing more about your solutions to better serve you with mine."
      copyright: "&copy;2017 Copier Warrior"
      youtube: http://www.youtube.com/embed/menlopU8jqc
      youtube_channel: https://youtube.com/channel/UC-BqyrLcd1uRE9zjAZuFDeg
      twitter: SalesRebellion
      facebook: salesrebellion
      office: (321) 567-5966
      mobile: (407) 719-2844
      email: dale.dupree85@gmail.com
      details:
        header: "The only copier sales guy that wields a Lightsaber!"
        body: "As a member of the community I serve on various boards and non-profit committees. I am a member of several chamber of commerce’s and an advocate for other industries, not just my own. I am bold, I have guts and I love to serve. I am not afraid to tell people that I am not the right fit and I am always looking to earn that extra bit of trust in my relationships through my business."
        features:
        - text: "I am a top tier Canon rep and recognized in the top 5 sales people for the state of FL"
          type:
          - star
          - users
          - paper-plane
      counters:
      - subject: ''
        count: 1
      feature:
        title: What His Clients Say About Him.
        percentages:
        - title: ''
          percent: 50
      testimonials:
      - name: ''
        title: ''
        quote: ''
      does:
        title: What He Does
        abilities:
        - heading: ''
          subheading: ''
          image: 'img/dale-copierwarrior-copierleases.jpg'
