---
pages:
- selling-local-podcast.md
- _posts/selling-local-podcast-1.md
hide_body: false
fields:
- name: layout
  label: Layout
  type: text
  hidden: false
  default: default
- name: fullname
  label: Fullname
  type: text
  hidden: false
  default: Dale Dupree
- name: title
  label: Title
  type: text
  hidden: false
  default: The Copier Warrior
- name: tagline
  label: Tagline
  type: text
  hidden: false
  default: Man, Myth, Sales Guy.
- name: fact
  label: Fact
  type: text
  hidden: false
  default: I was born to serve
- name: bio
  label: Bio
  type: textarea
  hidden: false
  default: I have been serving through this industry for over 10 years. My father
    before me is my mentor and the owner of the business where I sold my first copier,
    needless to say I have toner running through my blood. It is my goal to know and
    learn more about each individual business that I serve as I believe in a referral
    relationship and also knowing more about your solutions to better serve you with
    mine.
- name: copyright
  label: Copyright
  type: text
  hidden: false
  default: "&copy;2017 Copier Warrior"
- name: youtube
  label: Youtube
  type: text
  hidden: false
  default: http://www.youtube.com/embed/menlopU8jqc
- name: youtube_channel
  label: Youtube channel
  type: text
  hidden: false
  default: https://youtube.com/channel/UC-BqyrLcd1uRE9zjAZuFDeg
- name: twitter
  label: Twitter
  type: text
  hidden: false
  default: CopierWarrior
- name: facebook
  label: Facebook
  type: text
  hidden: false
  default: copierwarrior
- name: office
  label: Office
  type: text
  hidden: false
  default: "(321) 567-5966"
- name: mobile
  label: Mobile
  type: text
  hidden: false
  default: "(407) 719-2844"
- name: email
  label: Email
  type: text
  hidden: false
  default: dale.dupree85@gmail.com
- name: details
  label: Details
  type: field_group
  fields:
  - name: header
    label: Header
    type: text
    hidden: false
    default: ''
  - name: body
    label: Body
    type: textarea
    hidden: false
    default: ''
  - name: features
    label: Features
    type: field_group_list
    fields:
    - name: text
      label: Text
      type: text
      hidden: false
      default: ''
    - name: type
      label: Type
      type: list
      hidden: false
      default: ''
    hidden: false
    default: ''
  hidden: false
  default: 
- name: counters
  label: Counters
  type: field_group_list
  fields:
  - name: subject
    label: Subject
    type: text
    hidden: false
    default: ''
  - name: count
    label: Count
    type: text
    hidden: false
    default: ''
  hidden: false
  default:
  - subject: ''
    count: 1
- name: feature
  label: Feature
  type: field_group
  fields:
  - name: title
    label: Title
    type: text
    hidden: false
    default: ''
  - name: percentages
    label: Percentages
    type: field_group_list
    fields:
    - name: title
      label: Title
      type: text
      hidden: false
      default: ''
    - name: percent
      label: Percent
      type: text
      hidden: false
      default: ''
    hidden: false
    default: ''
  hidden: false
  default: 
- name: testimonials
  label: Testimonials
  type: field_group_list
  fields:
  - name: name
    label: Name
    type: text
    hidden: false
    default: ''
  - name: title
    label: Title
    type: text
    hidden: false
    default: ''
  - name: quote
    label: Quote
    type: text
    hidden: false
    default: ''
  hidden: false
  default:
  - name: ''
    title: ''
    quote: ''
- name: does
  label: Does
  type: field_group
  fields:
  - name: title
    label: Title
    type: text
    hidden: false
    default: ''
  - name: abilities
    label: Abilities
    type: field_group_list
    fields:
    - name: heading
      label: Heading
      type: text
      hidden: false
      default: ''
    - name: subheading
      label: Subheading
      type: text
      hidden: false
      default: ''
    - name: image
      label: Image
      type: text
      hidden: false
      default: ''
    hidden: false
    default: ''
  hidden: false
  default: 
